services:
  postgres:
    image: postgres:17-alpine
    platform: linux/arm64
    environment:
      POSTGRES_DB: homelab
      POSTGRES_USER: jeff_homelab
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGUSER: jeff_homelab          # Add this - sets default user
      PGDATABASE: homelab           # Add this - sets default database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: